#!/usr/local/cpanel/3rdparty/bin/perl

use strict;
use warnings;

my $user = 'stppmeda';   # ganti dengan username yang diinginkan

my $output = `/usr/local/cpanel/bin/uapi --user=$user --output=jsonpretty Ftp list_ftp 2>&1`;
print $output;
