#!/usr/local/cpanel/3rdparty/bin/perl

use strict;
use warnings;
use Data::Dumper;
use Cpanel::AdminBin::Call;

my $result = Cpanel::AdminBin::Call::call('Cpanel', 'ftp', 'LISTSTORE');

print Dumper($result);
